### PR TITLE
Set up project folder structure

### PR DESCRIPTION
**Pull request by pnilan**
1. npm init
    - Set up package.json
2. Added folder structure:
    - dist
    - spec (for test files)
    - src
        - assets
            - styles.css
            - favicon.ico (placeholder)
        - components
            - App.jsx
        - lib (for any helpers)
        - index.jsx
    - index.html
3. installed eslint, set up eslint
4. installed dotenv, react, react-dom

TO DO
- install webpack and setup webpack (Tim)
- install babel
- install testing library/libraries
- install way to serve files during dev (temp server)
- Different spot for index.html?

### CODE REVIEW

**Comment by timdecillis** [comment]
Hey, great job on this, Patrick! I'll go ahead and take a crack at merging your changes and then get to work on adding webpack and babel.

**Review by timdecillis — APPROVED** [review]
Lgtm!

**Comment by trilly-con-queso** [comment]
Agreed, this looks great! Thanks Patrick

**Review by trilly-con-queso — APPROVED** [review]
lgtm!

**Pull request merged**
