### PR TITLE
Config.js

### PR DESCRIPTION
**Pull request by timdecillis**
Config.js is set up, and now I know how directories work!

### CODE REVIEW

**Review by trilly-con-queso — CHANGES_REQUESTED** [review]
Hey Tim, I don't thing your config.js file was ignored in this PR  so we can see your token

**Comment by pnilan** [comment]
@timdecillis Can you also make the variable all caps? Like "TOKEN". All caps variables are considered constants.

**Comment by pnilan** [comment]
Can't approve this until the conflict is resolved.

**Comment by timdecillis** [comment]
Ok! It looks like all the conflicts are resolved and I checked out the branch on github and the config.js and bundle.js.map are properly ignored.

**Review by pnilan — APPROVED** [review]
👍

**Pull request merged**
